import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/Provider";
import NavBar from "@/components/navBar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Note-Taker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Toaster />
          <NavBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
